name: variational-doob
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.7
  - pip=23.3.2
  - openmm=8.1.1
  - mdtraj=1.9.8
  - tqdm=4.65.0
  - matplotlib=3.8.4
  - scipy=1.12.0
  - scikit-image=0.23.2
  - ParmEd=4.2.2
  - openpathsampling=1.6.1
  - jax=0.4.23
  - jaxlib=0.4.23
  - flax=0.8.3
  - notebook=7.0.8
  - POT=0.9.4
  - pip:
    - dmff @ git+https://github.com/deepmodeling/DMFF@v1.0.0
    - rdkit==2023.3.3
