save_dir: ./out/toy/dual_channel_single_gaussian

test_system: double_well_dual_channel
T: 1.0
xi: 0.1
gamma: 1.0

num_gaussians: 1
trainable_weights: False

epochs: 20000
BS: 512

num_paths: 1000
dt: 1e-3
