save_dir: ./out/aldp_diagonal_single_gaussian

start: ./files/AD_A.pdb
target: ./files/AD_B.pdb

ode: second_order
parameterization: diagonal
T: 1.0
temperature: 300
gamma: 1.0

num_gaussians: 1
trainable_weights: False
base_sigma: 1e-4

epochs: 50
BS: 256

num_paths: 256
dt: 1e-3
